//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gbim.Notification.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gbim.Notification.Api.EmailTemplate", typeof(EmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;Код подтверждения для учетной записи «Государственный банк информационных моделей»&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		#outlook a{{padding:0}}body{{width:100%!important}}.ReadMsgBody{{width:100%}}.ExternalClass{{width:100%}}body{{-webkit-text-size-adjust:none}}body{{margin:0;pad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfirmationCode {
            get {
                return ResourceManager.GetString("ConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;{0}&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		#outlook a{{padding:0}}body{{width:100%!important}}.ReadMsgBody{{width:100%}}.ExternalClass{{width:100%}}body{{-webkit-text-size-adjust:none}}body{{margin:0;padding:0}}img{{border:0;height:auto;line-height:100%;outline:none;text-decoration [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LocalizedSimpleMessage {
            get {
                return ResourceManager.GetString("LocalizedSimpleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;Код подтверждения для учетной записи «Государственный банк информационных моделей»&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		#outlook a{{padding:0}}body{{width:100%!important}}.ReadMsgBody{{width:100%}}.ExternalClass{{width:100%}}body{{-webkit-text-size-adjust:none}}body{{margin:0;pad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProfileActivated {
            get {
                return ResourceManager.GetString("ProfileActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;Код подтверждения для учетной записи «Государственный банк информационных моделей»&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		#outlook a{{padding:0}}body{{width:100%!important}}.ReadMsgBody{{width:100%}}.ExternalClass{{width:100%}}body{{-webkit-text-size-adjust:none}}body{{margin:0;pad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProfileDeactivated {
            get {
                return ResourceManager.GetString("ProfileDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;Код подтверждения для учетной записи «Государственный банк информационных моделей»&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		#outlook a{{padding:0}}body{{width:100%!important}}.ReadMsgBody{{width:100%}}.ExternalClass{{width:100%}}body{{-webkit-text-size-adjust:none}}body{{margin:0;pad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegRequestAccept {
            get {
                return ResourceManager.GetString("RegRequestAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;Код подтверждения для учетной записи «Государственный банк информационных моделей»&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		#outlook a{{padding:0}}body{{width:100%!important}}.ReadMsgBody{{width:100%}}.ExternalClass{{width:100%}}body{{-webkit-text-size-adjust:none}}body{{margin:0;pad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegRequestDeny {
            get {
                return ResourceManager.GetString("RegRequestDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;{0}&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		#outlook a{{padding:0}}body{{width:100%!important}}.ReadMsgBody{{width:100%}}.ExternalClass{{width:100%}}body{{-webkit-text-size-adjust:none}}body{{margin:0;padding:0}}img{{border:0;height:auto;line-height:100%;outline:none;text-decoration [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SimpleMessage {
            get {
                return ResourceManager.GetString("SimpleMessage", resourceCulture);
            }
        }
    }
}
