version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  waiter.api:
    image: ${DOCKER_REGISTRY-}waiterapi
    container_name: Waiters.Api
    build:
      context: .
      dockerfile: Waiters.Api/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "host=sql;port=5432;database=WaiterDb;username=waiter;password=MJFsdgfs%3423"
    ports:
      - "5101:80"
    networks:
      - dockerapi-dev

#  sql:
#    image: postgres:latest
#    container_name: sql
#    ports:
#      - "5433:5432"
#    restart: always
#    volumes:
#      - waiter_db_volume:/var/lib/postrgesql/data
#    environment:
#      POSTGRES_USER: "waiter"
#      POSTGRES_PASSWORD: "MJFsdgfs%3423"
#      POSTGRES_DB: "WaiterDb"
#    networks:
#      - dockerapi-dev

volumes:
  waiter_db_volume:

